version: "3"
services:
  # Apache with PHP (UI App)
  www:
    build: .
    ports:
      - "7170:80"  # Expose port 8080 on the host for the UI (instead of port 80)
    volumes:
      - ./www:/var/www/html  # Mount local www folder to container's /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html  # Ensure Apache serves the right directory
    networks:
      - app_network  # Use a custom network for better isolation

  # MySQL Database
  db:
    image: mysql:5.7.28
    ports:
      - "3307:3306"  # Expose port 3306 for MySQL access
    environment:
      MYSQL_DATABASE: cyfrif_campaign
      MYSQL_USER: campaign_user
      MYSQL_PASSWORD: campaign_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d  # Initialize database from dump folder
      - persistent:/var/lib/mysql  # Persist MySQL data across container restarts
    networks:
      - app_network  # Ensure MySQL and other services are in the same network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "82:80"  # Expose phpMyAdmin on port 82
    environment:
      PMA_HOST: db  # Link phpMyAdmin to the db service (MySQL)
      MYSQL_USER: campaign_user
      MYSQL_PASSWORD: campaign_password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network  # Same network for all services
    depends_on:
      - db  # Ensure phpMyAdmin starts after the database

# Define persistent volume for MySQL data storage
volumes:
  persistent:
    driver: local  # Ensure data is stored persistently across container restarts

# Define custom network for communication between containers
networks:
  app_network:
    driver: bridge
