version: "2"
services:
  # Apache with PHP (UI App)
  www:
    build: .  # Use the Dockerfile in the current directory
    ports:
      - "7175:80"  # Expose Apache on port 7170 (or change this as needed)
    volumes:
      - ./www:/var/www/html  # Mount the local code directory to the container's directory
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html  # Ensure Apache serves the right directory
    networks:
      - app_network

  # MySQL Database
  db:
    image: mysql:5.7.28
    ports:
      - "3352:3306"  # Expose MySQL on port 3352
    environment:
      MYSQL_DATABASE: cyfrif_campaign
      MYSQL_USER: campaign_user
      MYSQL_PASSWORD: campaign_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d  # Initialize database from dump
      - persistent:/var/lib/mysql  # Persist MySQL data
    networks:
      - app_network  # Connect MySQL and other services

  # phpMyAdmin for managing MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "82:80"  # Expose phpMyAdmin on port 82
    environment:
      PMA_HOST: db  # Connect phpMyAdmin to the MySQL container
      MYSQL_USER: campaign_user
      MYSQL_PASSWORD: campaign_password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network
    depends_on:
      - db

# Define persistent volume for MySQL data
volumes:
  persistent:
    driver: local

# Define custom network for isolated communication between containers
networks:
  app_network:
    driver: bridge
