version: "3.9" # Use a more recent version

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "9000:9000" # Expose the application port (assuming port 9000 from your Dockerfile)


  web:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8 # Use a more recent, supported MySQL version
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Use environment variables for secrets
      MYSQL_DATABASE: cakephp
      MYSQL_USER: cakeuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Use environment variables for secrets
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck: # Add healthcheck for database
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  app-network:
    driver: bridge
