version: '2'
# Define all services
services:
  # CakePHP application
  cakephp:
    build: .
    ports:
      - "4000:80"  # Exposing Apache server on port 4000
    depends_on:
      - mysql  # Dependency on MySQL container
    volumes:
      - ./www:/var/www/html  # Mount the working directory to the container
    environment:
      - SECURITY_SALT=ashjg23697sds97139871298ashk
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - VIRTUAL_HOST=cakephp.local  # Optional: if you're using a reverse proxy like NGINX
    networks:
      - app_network

  # MySQL service
  mysql:
    image: mysql:5.6.36
    volumes:
      - ./dump:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cyfrif_campaign
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

# Persistent data for MySQL
volumes:
  mysql_data:

# Custom network for isolated communication
networks:
  app_network:
    driver: bridge
